name: Build and deploy dapp - production

on:
  push:
    branches: [production]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV   
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10.23.0'
      - run: npm install
      - run: npm run build:production
      - name: generate version file
        run: echo $(date +"%Y-%m-%dT%H:%M:%S%z") - ${{env.RELEASE_VERSION}} - ${{ github.sha }}  > build/version.html
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/prod.key
          chmod 600 ~/.ssh/prod.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/prod.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.PRODUCTION_DEPLOY_USER }}
          SSH_KEY: ${{ secrets.PRODUCTION_DEPLOY_KEY }}
          SSH_HOST: ${{ secrets.PRODUCTION_DEPLOY_HOST }}
      - name: ls directory
        run: ssh prod 'ls ${{ secrets.PRODUCTION_DEPLOY_PATH }}'
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: build/
          remote_path: ${{ secrets.PRODUCTION_DEPLOY_PATH }}/${{ github.sha }} 
          remote_host: ${{ secrets.PRODUCTION_DEPLOY_HOST }}
          remote_user: ${{ secrets.PRODUCTION_DEPLOY_USER }}
          remote_key: ${{ secrets.PRODUCTION_DEPLOY_KEY }}
